#!/bin/bash
#$1 is the file name
#usage:this_script <filename>

#updates <filename> to ftp server
HOST='ftp.johng.altervista.org'
USER="johng"
PASSWD="***" #REPLACE WITH PASSWD
FILE="$1"
REMOTEPATH='/'

echo "test: filename: |"$1"|"

pftp -n $HOST <<END_SCRIPT
quote USER $USER
quote PASS $PASSWD
cd $REMOTEPATH
put $FILE 
quit
END_SCRIPT
exit 0
